
class Chef::Node
  def generate_dnsmasq_conf
    return nil if self['dnsmasq']['config'].nil?
    lines = []
    
    lines << '# Generated by Chef'
    lines << ''

    self['dnsmasq']['config'].each do |key,value_or_values|
      next if value_or_values.nil? # skip nil values -> support deleting a presetted value
      (value_or_values.kind_of?(Array) ? value_or_values : [ value_or_values ]).each do |value|
        if value.kind_of? TrueClass
          lines << "#{key}=#{value}"
        elsif value.kind_of? FalseClass
          next
        elsif value == ''
          next
        else
          lines << "#{key}=#{value.to_s}"
        end
      end
    end

    lines << ''
    lines.join "\n"
  end
end
